// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace protocol {
class EventReport;
struct EventReportDefaultTypeInternal;
extern EventReportDefaultTypeInternal _EventReport_default_instance_;
class FileRequest;
struct FileRequestDefaultTypeInternal;
extern FileRequestDefaultTypeInternal _FileRequest_default_instance_;
class MsgPayload;
struct MsgPayloadDefaultTypeInternal;
extern MsgPayloadDefaultTypeInternal _MsgPayload_default_instance_;
class ProcessRequest;
struct ProcessRequestDefaultTypeInternal;
extern ProcessRequestDefaultTypeInternal _ProcessRequest_default_instance_;
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol::EventReport* Arena::CreateMaybeMessage<::protocol::EventReport>(Arena*);
template<> ::protocol::FileRequest* Arena::CreateMaybeMessage<::protocol::FileRequest>(Arena*);
template<> ::protocol::MsgPayload* Arena::CreateMaybeMessage<::protocol::MsgPayload>(Arena*);
template<> ::protocol::ProcessRequest* Arena::CreateMaybeMessage<::protocol::ProcessRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol {

enum OpType : int {
  UNKNOW = 0,
  ADD_PROTECT_FILE = 1,
  REMOVE_PROTECT_FILE = 2,
  ADD_WHITE_PROCESS = 3,
  REMOVE_WHITE_PROCESS = 4,
  EVENT_REPORT = 5,
  HEARTBEAT = 6,
  OPT = 7,
  OpType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OpType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OpType_IsValid(int value);
constexpr OpType OpType_MIN = UNKNOW;
constexpr OpType OpType_MAX = OPT;
constexpr int OpType_ARRAYSIZE = OpType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OpType_descriptor();
template<typename T>
inline const std::string& OpType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OpType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OpType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OpType_descriptor(), enum_t_value);
}
inline bool OpType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OpType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OpType>(
    OpType_descriptor(), name, value);
}
// ===================================================================

class FileRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.FileRequest) */ {
 public:
  inline FileRequest() : FileRequest(nullptr) {}
  ~FileRequest() override;
  explicit PROTOBUF_CONSTEXPR FileRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileRequest(const FileRequest& from);
  FileRequest(FileRequest&& from) noexcept
    : FileRequest() {
    *this = ::std::move(from);
  }

  inline FileRequest& operator=(const FileRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileRequest& operator=(FileRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileRequest* internal_default_instance() {
    return reinterpret_cast<const FileRequest*>(
               &_FileRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileRequest& a, FileRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FileRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileRequest& from) {
    FileRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.FileRequest";
  }
  protected:
  explicit FileRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // @@protoc_insertion_point(class_scope:protocol.FileRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class ProcessRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.ProcessRequest) */ {
 public:
  inline ProcessRequest() : ProcessRequest(nullptr) {}
  ~ProcessRequest() override;
  explicit PROTOBUF_CONSTEXPR ProcessRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessRequest(const ProcessRequest& from);
  ProcessRequest(ProcessRequest&& from) noexcept
    : ProcessRequest() {
    *this = ::std::move(from);
  }

  inline ProcessRequest& operator=(const ProcessRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessRequest& operator=(ProcessRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessRequest* internal_default_instance() {
    return reinterpret_cast<const ProcessRequest*>(
               &_ProcessRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProcessRequest& a, ProcessRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessRequest& from) {
    ProcessRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.ProcessRequest";
  }
  protected:
  explicit ProcessRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // @@protoc_insertion_point(class_scope:protocol.ProcessRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class EventReport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.EventReport) */ {
 public:
  inline EventReport() : EventReport(nullptr) {}
  ~EventReport() override;
  explicit PROTOBUF_CONSTEXPR EventReport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EventReport(const EventReport& from);
  EventReport(EventReport&& from) noexcept
    : EventReport() {
    *this = ::std::move(from);
  }

  inline EventReport& operator=(const EventReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline EventReport& operator=(EventReport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EventReport& default_instance() {
    return *internal_default_instance();
  }
  static inline const EventReport* internal_default_instance() {
    return reinterpret_cast<const EventReport*>(
               &_EventReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(EventReport& a, EventReport& b) {
    a.Swap(&b);
  }
  inline void Swap(EventReport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EventReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EventReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EventReport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EventReport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EventReport& from) {
    EventReport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EventReport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.EventReport";
  }
  protected:
  explicit EventReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommFieldNumber = 1,
    kInodeFieldNumber = 2,
    kOpFieldNumber = 3,
    kSuccessFieldNumber = 4,
  };
  // string comm = 1;
  void clear_comm();
  const std::string& comm() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_comm(ArgT0&& arg0, ArgT... args);
  std::string* mutable_comm();
  PROTOBUF_NODISCARD std::string* release_comm();
  void set_allocated_comm(std::string* comm);
  private:
  const std::string& _internal_comm() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_comm(const std::string& value);
  std::string* _internal_mutable_comm();
  public:

  // uint64 inode = 2;
  void clear_inode();
  uint64_t inode() const;
  void set_inode(uint64_t value);
  private:
  uint64_t _internal_inode() const;
  void _internal_set_inode(uint64_t value);
  public:

  // uint32 op = 3;
  void clear_op();
  uint32_t op() const;
  void set_op(uint32_t value);
  private:
  uint32_t _internal_op() const;
  void _internal_set_op(uint32_t value);
  public:

  // bool success = 4;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.EventReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr comm_;
    uint64_t inode_;
    uint32_t op_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class MsgPayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.MsgPayload) */ {
 public:
  inline MsgPayload() : MsgPayload(nullptr) {}
  ~MsgPayload() override;
  explicit PROTOBUF_CONSTEXPR MsgPayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgPayload(const MsgPayload& from);
  MsgPayload(MsgPayload&& from) noexcept
    : MsgPayload() {
    *this = ::std::move(from);
  }

  inline MsgPayload& operator=(const MsgPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPayload& operator=(MsgPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MsgPayload& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kFileReq = 1,
    kProcReq = 2,
    kEventRpt = 3,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const MsgPayload* internal_default_instance() {
    return reinterpret_cast<const MsgPayload*>(
               &_MsgPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MsgPayload& a, MsgPayload& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgPayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MsgPayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MsgPayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MsgPayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MsgPayload& from) {
    MsgPayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.MsgPayload";
  }
  protected:
  explicit MsgPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileReqFieldNumber = 1,
    kProcReqFieldNumber = 2,
    kEventRptFieldNumber = 3,
  };
  // .protocol.FileRequest file_req = 1;
  bool has_file_req() const;
  private:
  bool _internal_has_file_req() const;
  public:
  void clear_file_req();
  const ::protocol::FileRequest& file_req() const;
  PROTOBUF_NODISCARD ::protocol::FileRequest* release_file_req();
  ::protocol::FileRequest* mutable_file_req();
  void set_allocated_file_req(::protocol::FileRequest* file_req);
  private:
  const ::protocol::FileRequest& _internal_file_req() const;
  ::protocol::FileRequest* _internal_mutable_file_req();
  public:
  void unsafe_arena_set_allocated_file_req(
      ::protocol::FileRequest* file_req);
  ::protocol::FileRequest* unsafe_arena_release_file_req();

  // .protocol.ProcessRequest proc_req = 2;
  bool has_proc_req() const;
  private:
  bool _internal_has_proc_req() const;
  public:
  void clear_proc_req();
  const ::protocol::ProcessRequest& proc_req() const;
  PROTOBUF_NODISCARD ::protocol::ProcessRequest* release_proc_req();
  ::protocol::ProcessRequest* mutable_proc_req();
  void set_allocated_proc_req(::protocol::ProcessRequest* proc_req);
  private:
  const ::protocol::ProcessRequest& _internal_proc_req() const;
  ::protocol::ProcessRequest* _internal_mutable_proc_req();
  public:
  void unsafe_arena_set_allocated_proc_req(
      ::protocol::ProcessRequest* proc_req);
  ::protocol::ProcessRequest* unsafe_arena_release_proc_req();

  // .protocol.EventReport event_rpt = 3;
  bool has_event_rpt() const;
  private:
  bool _internal_has_event_rpt() const;
  public:
  void clear_event_rpt();
  const ::protocol::EventReport& event_rpt() const;
  PROTOBUF_NODISCARD ::protocol::EventReport* release_event_rpt();
  ::protocol::EventReport* mutable_event_rpt();
  void set_allocated_event_rpt(::protocol::EventReport* event_rpt);
  private:
  const ::protocol::EventReport& _internal_event_rpt() const;
  ::protocol::EventReport* _internal_mutable_event_rpt();
  public:
  void unsafe_arena_set_allocated_event_rpt(
      ::protocol::EventReport* event_rpt);
  ::protocol::EventReport* unsafe_arena_release_event_rpt();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:protocol.MsgPayload)
 private:
  class _Internal;
  void set_has_file_req();
  void set_has_proc_req();
  void set_has_event_rpt();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::protocol::FileRequest* file_req_;
      ::protocol::ProcessRequest* proc_req_;
      ::protocol::EventReport* event_rpt_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileRequest

// string path = 1;
inline void FileRequest::clear_path() {
  _impl_.path_.ClearToEmpty();
}
inline const std::string& FileRequest::path() const {
  // @@protoc_insertion_point(field_get:protocol.FileRequest.path)
  return _internal_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileRequest::set_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.FileRequest.path)
}
inline std::string* FileRequest::mutable_path() {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:protocol.FileRequest.path)
  return _s;
}
inline const std::string& FileRequest::_internal_path() const {
  return _impl_.path_.Get();
}
inline void FileRequest::_internal_set_path(const std::string& value) {
  
  _impl_.path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileRequest::_internal_mutable_path() {
  
  return _impl_.path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileRequest::release_path() {
  // @@protoc_insertion_point(field_release:protocol.FileRequest.path)
  return _impl_.path_.Release();
}
inline void FileRequest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  _impl_.path_.SetAllocated(path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocol.FileRequest.path)
}

// -------------------------------------------------------------------

// ProcessRequest

// string path = 1;
inline void ProcessRequest::clear_path() {
  _impl_.path_.ClearToEmpty();
}
inline const std::string& ProcessRequest::path() const {
  // @@protoc_insertion_point(field_get:protocol.ProcessRequest.path)
  return _internal_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessRequest::set_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.ProcessRequest.path)
}
inline std::string* ProcessRequest::mutable_path() {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:protocol.ProcessRequest.path)
  return _s;
}
inline const std::string& ProcessRequest::_internal_path() const {
  return _impl_.path_.Get();
}
inline void ProcessRequest::_internal_set_path(const std::string& value) {
  
  _impl_.path_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessRequest::_internal_mutable_path() {
  
  return _impl_.path_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessRequest::release_path() {
  // @@protoc_insertion_point(field_release:protocol.ProcessRequest.path)
  return _impl_.path_.Release();
}
inline void ProcessRequest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  _impl_.path_.SetAllocated(path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocol.ProcessRequest.path)
}

// -------------------------------------------------------------------

// EventReport

// string comm = 1;
inline void EventReport::clear_comm() {
  _impl_.comm_.ClearToEmpty();
}
inline const std::string& EventReport::comm() const {
  // @@protoc_insertion_point(field_get:protocol.EventReport.comm)
  return _internal_comm();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EventReport::set_comm(ArgT0&& arg0, ArgT... args) {
 
 _impl_.comm_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protocol.EventReport.comm)
}
inline std::string* EventReport::mutable_comm() {
  std::string* _s = _internal_mutable_comm();
  // @@protoc_insertion_point(field_mutable:protocol.EventReport.comm)
  return _s;
}
inline const std::string& EventReport::_internal_comm() const {
  return _impl_.comm_.Get();
}
inline void EventReport::_internal_set_comm(const std::string& value) {
  
  _impl_.comm_.Set(value, GetArenaForAllocation());
}
inline std::string* EventReport::_internal_mutable_comm() {
  
  return _impl_.comm_.Mutable(GetArenaForAllocation());
}
inline std::string* EventReport::release_comm() {
  // @@protoc_insertion_point(field_release:protocol.EventReport.comm)
  return _impl_.comm_.Release();
}
inline void EventReport::set_allocated_comm(std::string* comm) {
  if (comm != nullptr) {
    
  } else {
    
  }
  _impl_.comm_.SetAllocated(comm, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.comm_.IsDefault()) {
    _impl_.comm_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protocol.EventReport.comm)
}

// uint64 inode = 2;
inline void EventReport::clear_inode() {
  _impl_.inode_ = uint64_t{0u};
}
inline uint64_t EventReport::_internal_inode() const {
  return _impl_.inode_;
}
inline uint64_t EventReport::inode() const {
  // @@protoc_insertion_point(field_get:protocol.EventReport.inode)
  return _internal_inode();
}
inline void EventReport::_internal_set_inode(uint64_t value) {
  
  _impl_.inode_ = value;
}
inline void EventReport::set_inode(uint64_t value) {
  _internal_set_inode(value);
  // @@protoc_insertion_point(field_set:protocol.EventReport.inode)
}

// uint32 op = 3;
inline void EventReport::clear_op() {
  _impl_.op_ = 0u;
}
inline uint32_t EventReport::_internal_op() const {
  return _impl_.op_;
}
inline uint32_t EventReport::op() const {
  // @@protoc_insertion_point(field_get:protocol.EventReport.op)
  return _internal_op();
}
inline void EventReport::_internal_set_op(uint32_t value) {
  
  _impl_.op_ = value;
}
inline void EventReport::set_op(uint32_t value) {
  _internal_set_op(value);
  // @@protoc_insertion_point(field_set:protocol.EventReport.op)
}

// bool success = 4;
inline void EventReport::clear_success() {
  _impl_.success_ = false;
}
inline bool EventReport::_internal_success() const {
  return _impl_.success_;
}
inline bool EventReport::success() const {
  // @@protoc_insertion_point(field_get:protocol.EventReport.success)
  return _internal_success();
}
inline void EventReport::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void EventReport::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:protocol.EventReport.success)
}

// -------------------------------------------------------------------

// MsgPayload

// .protocol.FileRequest file_req = 1;
inline bool MsgPayload::_internal_has_file_req() const {
  return payload_case() == kFileReq;
}
inline bool MsgPayload::has_file_req() const {
  return _internal_has_file_req();
}
inline void MsgPayload::set_has_file_req() {
  _impl_._oneof_case_[0] = kFileReq;
}
inline void MsgPayload::clear_file_req() {
  if (_internal_has_file_req()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.file_req_;
    }
    clear_has_payload();
  }
}
inline ::protocol::FileRequest* MsgPayload::release_file_req() {
  // @@protoc_insertion_point(field_release:protocol.MsgPayload.file_req)
  if (_internal_has_file_req()) {
    clear_has_payload();
    ::protocol::FileRequest* temp = _impl_.payload_.file_req_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.file_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::FileRequest& MsgPayload::_internal_file_req() const {
  return _internal_has_file_req()
      ? *_impl_.payload_.file_req_
      : reinterpret_cast< ::protocol::FileRequest&>(::protocol::_FileRequest_default_instance_);
}
inline const ::protocol::FileRequest& MsgPayload::file_req() const {
  // @@protoc_insertion_point(field_get:protocol.MsgPayload.file_req)
  return _internal_file_req();
}
inline ::protocol::FileRequest* MsgPayload::unsafe_arena_release_file_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.MsgPayload.file_req)
  if (_internal_has_file_req()) {
    clear_has_payload();
    ::protocol::FileRequest* temp = _impl_.payload_.file_req_;
    _impl_.payload_.file_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MsgPayload::unsafe_arena_set_allocated_file_req(::protocol::FileRequest* file_req) {
  clear_payload();
  if (file_req) {
    set_has_file_req();
    _impl_.payload_.file_req_ = file_req;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.MsgPayload.file_req)
}
inline ::protocol::FileRequest* MsgPayload::_internal_mutable_file_req() {
  if (!_internal_has_file_req()) {
    clear_payload();
    set_has_file_req();
    _impl_.payload_.file_req_ = CreateMaybeMessage< ::protocol::FileRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.file_req_;
}
inline ::protocol::FileRequest* MsgPayload::mutable_file_req() {
  ::protocol::FileRequest* _msg = _internal_mutable_file_req();
  // @@protoc_insertion_point(field_mutable:protocol.MsgPayload.file_req)
  return _msg;
}

// .protocol.ProcessRequest proc_req = 2;
inline bool MsgPayload::_internal_has_proc_req() const {
  return payload_case() == kProcReq;
}
inline bool MsgPayload::has_proc_req() const {
  return _internal_has_proc_req();
}
inline void MsgPayload::set_has_proc_req() {
  _impl_._oneof_case_[0] = kProcReq;
}
inline void MsgPayload::clear_proc_req() {
  if (_internal_has_proc_req()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.proc_req_;
    }
    clear_has_payload();
  }
}
inline ::protocol::ProcessRequest* MsgPayload::release_proc_req() {
  // @@protoc_insertion_point(field_release:protocol.MsgPayload.proc_req)
  if (_internal_has_proc_req()) {
    clear_has_payload();
    ::protocol::ProcessRequest* temp = _impl_.payload_.proc_req_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.proc_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::ProcessRequest& MsgPayload::_internal_proc_req() const {
  return _internal_has_proc_req()
      ? *_impl_.payload_.proc_req_
      : reinterpret_cast< ::protocol::ProcessRequest&>(::protocol::_ProcessRequest_default_instance_);
}
inline const ::protocol::ProcessRequest& MsgPayload::proc_req() const {
  // @@protoc_insertion_point(field_get:protocol.MsgPayload.proc_req)
  return _internal_proc_req();
}
inline ::protocol::ProcessRequest* MsgPayload::unsafe_arena_release_proc_req() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.MsgPayload.proc_req)
  if (_internal_has_proc_req()) {
    clear_has_payload();
    ::protocol::ProcessRequest* temp = _impl_.payload_.proc_req_;
    _impl_.payload_.proc_req_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MsgPayload::unsafe_arena_set_allocated_proc_req(::protocol::ProcessRequest* proc_req) {
  clear_payload();
  if (proc_req) {
    set_has_proc_req();
    _impl_.payload_.proc_req_ = proc_req;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.MsgPayload.proc_req)
}
inline ::protocol::ProcessRequest* MsgPayload::_internal_mutable_proc_req() {
  if (!_internal_has_proc_req()) {
    clear_payload();
    set_has_proc_req();
    _impl_.payload_.proc_req_ = CreateMaybeMessage< ::protocol::ProcessRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.proc_req_;
}
inline ::protocol::ProcessRequest* MsgPayload::mutable_proc_req() {
  ::protocol::ProcessRequest* _msg = _internal_mutable_proc_req();
  // @@protoc_insertion_point(field_mutable:protocol.MsgPayload.proc_req)
  return _msg;
}

// .protocol.EventReport event_rpt = 3;
inline bool MsgPayload::_internal_has_event_rpt() const {
  return payload_case() == kEventRpt;
}
inline bool MsgPayload::has_event_rpt() const {
  return _internal_has_event_rpt();
}
inline void MsgPayload::set_has_event_rpt() {
  _impl_._oneof_case_[0] = kEventRpt;
}
inline void MsgPayload::clear_event_rpt() {
  if (_internal_has_event_rpt()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.event_rpt_;
    }
    clear_has_payload();
  }
}
inline ::protocol::EventReport* MsgPayload::release_event_rpt() {
  // @@protoc_insertion_point(field_release:protocol.MsgPayload.event_rpt)
  if (_internal_has_event_rpt()) {
    clear_has_payload();
    ::protocol::EventReport* temp = _impl_.payload_.event_rpt_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.event_rpt_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protocol::EventReport& MsgPayload::_internal_event_rpt() const {
  return _internal_has_event_rpt()
      ? *_impl_.payload_.event_rpt_
      : reinterpret_cast< ::protocol::EventReport&>(::protocol::_EventReport_default_instance_);
}
inline const ::protocol::EventReport& MsgPayload::event_rpt() const {
  // @@protoc_insertion_point(field_get:protocol.MsgPayload.event_rpt)
  return _internal_event_rpt();
}
inline ::protocol::EventReport* MsgPayload::unsafe_arena_release_event_rpt() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protocol.MsgPayload.event_rpt)
  if (_internal_has_event_rpt()) {
    clear_has_payload();
    ::protocol::EventReport* temp = _impl_.payload_.event_rpt_;
    _impl_.payload_.event_rpt_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MsgPayload::unsafe_arena_set_allocated_event_rpt(::protocol::EventReport* event_rpt) {
  clear_payload();
  if (event_rpt) {
    set_has_event_rpt();
    _impl_.payload_.event_rpt_ = event_rpt;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protocol.MsgPayload.event_rpt)
}
inline ::protocol::EventReport* MsgPayload::_internal_mutable_event_rpt() {
  if (!_internal_has_event_rpt()) {
    clear_payload();
    set_has_event_rpt();
    _impl_.payload_.event_rpt_ = CreateMaybeMessage< ::protocol::EventReport >(GetArenaForAllocation());
  }
  return _impl_.payload_.event_rpt_;
}
inline ::protocol::EventReport* MsgPayload::mutable_event_rpt() {
  ::protocol::EventReport* _msg = _internal_mutable_event_rpt();
  // @@protoc_insertion_point(field_mutable:protocol.MsgPayload.event_rpt)
  return _msg;
}

inline bool MsgPayload::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void MsgPayload::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline MsgPayload::PayloadCase MsgPayload::payload_case() const {
  return MsgPayload::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protocol::OpType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protocol::OpType>() {
  return ::protocol::OpType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
